version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "VrchAndroid/build.gradle" }}-{{ checksum  "VrchAndroid/app/build.gradle" }}
      - run:
          name: Set build.properties
          command: mv ci.properties build.properties
          working_directory: VrchAndroid
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
          working_directory: VrchAndroid
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "VrchAndroid/build.gradle" }}-{{ checksum  "VrchAndroid/app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
          working_directory: VrchAndroid
      - store_artifacts:
          path: VrchAndroid/app/build/reports
          destination: reports
      - store_test_results:
          path: VrchAndroid/app/build/test-results
