// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vrch/voice.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Vrch {

  /// <summary>Holder for reflection information generated from vrch/voice.proto</summary>
  public static partial class VoiceReflection {

    #region Descriptor
    /// <summary>File descriptor for vrch/voice.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VoiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChB2cmNoL3ZvaWNlLnByb3RvEgR2cmNoIhYKBVZvaWNlEg0KBXZvaWNlGAEg",
            "ASgMYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Vrch.Voice), global::Vrch.Voice.Parser, new[]{ "Voice_" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Voice : pb::IMessage<Voice> {
    private static readonly pb::MessageParser<Voice> _parser = new pb::MessageParser<Voice>(() => new Voice());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Voice> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Vrch.VoiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Voice() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Voice(Voice other) : this() {
      voice_ = other.voice_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Voice Clone() {
      return new Voice(this);
    }

    /// <summary>Field number for the "voice" field.</summary>
    public const int Voice_FieldNumber = 1;
    private pb::ByteString voice_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Voice_ {
      get { return voice_; }
      set {
        voice_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Voice);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Voice other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Voice_ != other.Voice_) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Voice_.Length != 0) hash ^= Voice_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Voice_.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Voice_);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Voice_.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Voice_);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Voice other) {
      if (other == null) {
        return;
      }
      if (other.Voice_.Length != 0) {
        Voice_ = other.Voice_;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Voice_ = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
