# The configuration schema is defined by service.proto file
# https://github.com/googleapis/googleapis/blob/master/google/api/service.proto
type: google.api.Service
config_version: 3

#
# Name of the service configuration.
#
name: vrch.endpoints.vrch-172501.cloud.goog

#
# API title to appear in the user interface (Google Cloud Console).
#
title: Vrch gRPC API
apis:
- name: vrch.VrchService
- name: vrch.VrClusterService

#
# API usage restrictions.
#
usage:
  rules:
  # methods can be called without an API Key.
  - selector: vrch.VrchService.Talk
    allow_unregistered_calls: true

  - selector: vrch.VrClusterService.Join
    allow_unregistered_calls: true
