apiVersion: v1
kind: Service
metadata:
  name: esp-grpc-vrch
spec:
  ports:
  # Port that accepts gRPC and JSON/HTTP2 requests over HTTP.
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http2
  selector:
    app: esp-grpc-vrch
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esp-grpc-vrch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: esp-grpc-vrch
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "-P", "9000",
          "-s", "{SERVICE_NAME}",
          "-v", "{SERVICE_CONFIG_ID}",
          "-a", "grpc://127.0.0.1:8000"
        ]
        ports:
          - containerPort: 9000
      - name: vrchgrpc
        image: nokamotohub/vrchgrpc
        env:
        - name: GRPC_PORT
          value: "8000"
        - name: API_KEY
          value: "{API_KEY}"
        ports:
          - containerPort: 8000
